name: CI

on:
  pull:
    branches: [main]



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recupérer le code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Installer les dépendances  
        run: npm ci

      - name: Vérifier le code
        run: npm run lint
        